CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="ZephyrTempNode"
CONFIG_BT_MAX_CONN=1

CONFIG_BT_GATT_SERVICE_CHANGED=y
CONFIG_SETTINGS=y

CONFIG_PRINTK=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y